Document: siengine
Title: Debian siengine Manual
Author: <insert document author here>
Abstract: This manual describes what siengine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/siengine/siengine.sgml.gz

Format: postscript
Files: /usr/share/doc/siengine/siengine.ps.gz

Format: text
Files: /usr/share/doc/siengine/siengine.text.gz

Format: HTML
Index: /usr/share/doc/siengine/html/index.html
Files: /usr/share/doc/siengine/html/*.html
